### ISSUE TITLE
Support fastapi 0.83.0

### ISSUE THREAD

**Issue by nstylo** [arthurio/fastapi-filter#103]
Started a new project using fastapi 0.83.0 recently. Fastapi-filter does not support versions higher than 0.81.0. It would be nice to support newer fastapi versions. For now will use 0.81.0. Thanks!

**Comment by arthurio** [comment]
I'll merge the dependabot updates and make a release in the coming days (if not tonight).

**Comment by arthurio** [comment]
Done: https://github.com/arthurio/fastapi-filter/releases/tag/v0.1.4
