### ISSUE TITLE
FastAPI Filter Query Param description not appearing

### ISSUE THREAD

**Issue by piotr-gregrowski** [arthurio/fastapi-filter#148]
Query fields in the filter are not correctly displaying the description in the generated API docs. Also not seeing the *required tag

Example code:
```
class ExampleFilter(Filter):
    filter_field_with_desc: str = Query(description="description won't show up")


@app.get("", status_code=HTTP_200_OK, operation_id="test_endpoint")
async def test_endpoint(
    request: Request,
    filter: ExampleFilter = FilterDepends(ExampleFilter),
    field_with_desc: str = Query(description="description will show up"),
):
    pass
```

<img width="662" alt="Screen Shot 2022-10-21 at 10 57 05 AM" src="https://user-images.githubusercontent.com/86212719/197226082-8e0bed5b-2735-4a5a-9d8c-d78122da3c2d.png">

This is not a breaking bug, but would be nice to have!

**Comment by arthurio** [comment]
Hi @piotr-gregrowski , thanks for submitting an issue with an example and screenshot, very helpful 💯 
Regarding the "required", https://github.com/arthurio/fastapi-filter/pull/152 will fix it. For the "description" piece, it's an open issue in FastApi https://github.com/tiangolo/fastapi/issues/4700 but I have added an example in the PR for the "workaround".

**Comment by piotr-gregrowski** [comment]
Thank you @arthurio!
