### ISSUE TITLE
Filter float by search_model_fields

### ISSUE THREAD

**Issue by christianramcke** [arthurio/fastapi-filter#246]
Hello Arthurio,

if one or more fields in `search_model_fields` are floats, there will be no usable result by the filter.

For example:
```
class ArticleFilter(Filter):
    search: Optional[str]
    ean: Optional[float]
    description: Optional[str]

    class Constants(Filter.Constants):
        model = Order
        search_field_name = "search"
        search_model_fields = ["ean", "description"]
```

In my case there are no results because of the float datatype. It must be cast to string or need to use with equals operation (not ilike).

I found [this article on StackOverflow](https://stackoverflow.com/questions/15950705/using-like-to-match-floats-when-rounding-is-not-wanted). I hope you can help me.

I use [SQLAlchemy](https://sqlalchemy.org/) as ORM with MSSQL.

Thank you alot for this fine piece of software <3 <3

**Comment by arthurio** [comment]
Since I haven't heard back from you I'll close this. Feel free to create a new issue with more details.
