### ISSUE TITLE
Support for postgis/geoalchemy functions.

### ISSUE THREAD

**Issue by voney** [arthurio/fastapi-filter#258]
Hi,

I'm interested in writing a PR to include the ability to do PostGis queries with this library. Would you be open to reviewing and accepting it assuming it passes tests?

Cheers,

Voney

Reference:

https://geoalchemy-2.readthedocs.io/en/0.3/_modules/geoalchemy2/comparator.html#Comparator.distance_centroid
https://postgis.net/docs/reference.html

**Comment by arthurio** [comment]
Hi Voney,

I don't have experience with postgis so a PR would be very welcome and I'll do my best to review it 😄
