### ISSUE TITLE
Using Filter class in sqlalchemy filter function

### ISSUE THREAD

**Issue by quydx** [arthurio/fastapi-filter#292]
I read the docs and saw this is how we can use the UserFilter Class:
```
@app.get("/users", response_model=list[UserOut])
async def get_users(user_filter: UserFilter = FilterDepends(UserFilter), db: AsyncSession = Depends(get_db)) -> Any:
    query = user_filter.filter(select(User).outerjoin(Address))   # 
    result = await db.execute(query)
    return result.scalars().all()
```
But I want to use UserFilter like that 
```
engine = create_engine(SQLALCHEMY_DATABASE_URI)
Session = sessionmaker(bind=self.engine)
objs = session.query(User).filter(user_filter).all()
```
Do we have any way to do this? Thank!

**Comment by arthurio** [comment]
Hi @quydx the `filter` function takes care of a couple of things to make the filtering work, especially for the related relations. There is nothing currently that could support `objs = session.query(User).filter(user_filter).all()`, could you explain a little bit what is your requirement for needing this approach?

**Comment by quydx** [comment]
@arthurio Thanks for the quick response. The above approach is how I implement my current application. Currently, I pass a dictionary as input for my filter module
And with each key, value of Dict I use
` dict_filter.append(getattr(SomeModel, key) == value)`
And then I use
`objs = session.query(SomeModel).filter(dict_filter).all()`
I want to keep my current approach and simply replace my filter dictionary with this library Filter class.
I don't want generate any text query and then execute it with 
`session.execute(query)`

**Comment by arthurio** [comment]
I don't really see the point of using the `Filter` class if it's not part of your route. The main point of the library is to reduce the churn of defining query strings for filtering and make it possible to re-use common field filters. Could you share a minimal example of one of your routes with your existing approach?
