### ISSUE TITLE
Can you add `startswith` as a keyword for prefix matching

### ISSUE THREAD

**Issue by mkdir700** [arthurio/fastapi-filter#299]
```
"startswith": lambda value: ("like", f"{value}%"), 
```

Of course, you can abbreviate startswith, just express the meaning of its prefix match

https://github.com/arthurio/fastapi-filter/blob/b40f814b3e1d99ccf1cf9c93458ce6368b2ff084/fastapi_filter/contrib/sqlalchemy/filter.py#L20

**Comment by arthurio** [comment]
🤔 I guess a better way would be to just remove the `%` from the `like` and `ilike` and let users pass it in explicitly as they see fit... So current `?my_field__like=test` would become `?my_field__like=%25test%25`. WDYT?

**Comment by mkdir700** [comment]
Yes, I think this approach is feasible, but now we have a compatibility issue. Users who previously used `like` will assume that `like` means `%keyword%`.
