### ISSUE TITLE
Support for fastapi 0.100 hence pydantic 2.0

### ISSUE THREAD

**Issue by anryangelov** [arthurio/fastapi-filter#439]
Hello, very nice library but is there any plan for supporting fastapi 0.100 soon?

**Comment by arthurio** [comment]
Yes, I have been pretty swamped this summer but I'll try to get to it as soon as possible. As always, PRs are welcome 😉

**Comment by maxim1770** [comment]
We are waiting very much!

**Comment by Kastakin** [comment]
For what is worth I am testing pull request #447 with `fastapi=0.103.0` and `pydantic=2.3.0`. Everything seems to be working fine for the time being in our project.

**Comment by arthurio** [comment]
@Kastakin Thank you for reporting real use feedback! 👏🏻 
I'm going to spend some time on this this week.

**Comment by johnybx** [comment]
@Kastakin if you want you can try latest commit - the breaking changes were removed.

**Comment by k00000han** [comment]
I tried to use this library on Pydentic 2.3.0 + FastAPI 0.103 + SQLAlchemy 2.0, I got version conflict errors and I can’t use this library, although I really need to implement filtering now and I can’t find anything sensible to implement my task
Will there be support for new versions?

**Comment by FerCalatayud** [comment]
@k00000han  There's already a PR that passed all the tests, #447 . They just need to review it en merge it when they can. Thanks to the contributor and @arthurio for their work, truly.

**Comment by FerCalatayud** [comment]
We now have version 1.0.0, which resolves this issue. Thank you for the work, it is much appreciated. @arthurio @johnybx
