### ISSUE TITLE
question : Filter a dict?

### ISSUE THREAD

**Issue by gehal4** [arthurio/fastapi-filter#442]
Hi all, 

I have a case where I'm trying to filter a field of a DictField?

Like so : `[api_url]/?location.country=CH`
where the document in mongo looks like : 

````json
{
    "some_field": "some_value",
    "location" :{
      "city":"Zurich",
      "country": "CH"
    }
}
````

Is this possible to do using fastapi-filter ? I didn't find something close to this in the documentation. 
Does anyone know how can I achieve this type of filtering ?

**Comment by gehal4** [comment]
Actually figured it out how to do this, just by adding `location` (dict) and its filed `country` with mongoengin language like `location__country` : 
````py
class ModelFilter(Filter):
    location__country: Optional[str]
````
Dind't find it in the documentation anywhere here, as maybe it's assumed that you need to have some mongoegine basic knowledge.

**Comment by arthurio** [comment]
Hi @gehal4 

Glad you figured it out, and yes the documentation can use some additions... PRs are welcome ;)

**Comment by berendovychRB** [comment]
Hey @arthurio 
I use sqlalchemy, is it possible to filter dict field?
I need to get records that have search value in dict values

for example
```
services: dict  # field in object

obj_from_db.services = {"service_1": 1, "service_2": 2}
input_filter_value = 1
```

and if object in db has 1 in values of services, return it
