### ISSUE TITLE
How to sort and filter at the same time

### ISSUE THREAD

**Issue by na0495** [arthurio/fastapi-filter#449]
I'm building an api where i have to sort and filter, how could i implement that, cause it not really clear on the documentation ?

**Comment by arthurio** [comment]
Hi @na0495, I know that the documentation needs to be updated and improved but it's hard to find time for all the things... Have you looked at the examples folder? https://github.com/arthurio/fastapi-filter/blob/main/examples/fastapi_filter_sqlalchemy.py

**Comment by na0495** [comment]
Hi @arthurio i did manage to solve the problem thank you, in order hand i could help improve the documentation if you want!

**Comment by arthurio** [comment]
Any help would be appreciated 👍🏻
