### ISSUE TITLE
Filters don't support repeating key pattern for list type parameters

### ISSUE THREAD

**Issue by nico-martinucci** [arthurio/fastapi-filter#472]
Currently, `Filter.filter` supports comma-separated list params like...
```
?foo__in=bar,qux
```
...but does not support repeating key list params, like...
```
?foo__in=bar&foo__in=qux
```
...which is also an accepted pattern for representing a list param in the query string. Would be great to have this feature added in the future. Happy to help out if there's a preferred approach, but I think this could be a bit more complicated than first glance.

**Comment by arthurio** [comment]
Yeah there is no standard and I just picked the one I was familiar with, similar to `django-filter`. I personally really don't like the repeating key pattern so I'm not going to spend time on this but I'm open to the idea, PRs welcome!
